[versions]
# Plugins
shadow = "9.3.0"
plugin-yml = "0.9.0"
run-paper = "3.0.2"
fabric-loom = "1.15-SNAPSHOT"

# Dependencies
tomlj = "1.1.1"
spigot-api = "1.21.1-R0.1-SNAPSHOT"
lombok = "1.18.42"
jetbrains-annotations = "26.0.2-1"
hoglin = "1.3.0"
cloud = "2.0.0"
cloud-bukkit = "2.0.0-beta.14"
cloud-paper = "2.0.0-beta.14"
cloud-velocity = "2.0.0-beta.14"
cloud-bungee = "2.0.0-beta.14"
cloud-fabric = "2.0.0-beta.9"
uuid-generator = "5.1.0"
velocity-api = "3.5.0-SNAPSHOT"
bungeecord-api = "1.21-R0.4"
minecraft = "1.21.1"
fabric-loader = "0.19.2"
fabric-api = "0.116.11+1.21.1"
jackson = "2.13.0"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
plugin-yml-bukkit = { id = "de.eldoria.plugin-yml.bukkit", version.ref = "plugin-yml" }
plugin-yml-bungee = { id = "de.eldoria.plugin-yml.bungee", version.ref = "plugin-yml" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }

[libraries]
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot-api" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
hoglin = { module = "gg.hoglin:sdk", version.ref = "hoglin" }
cloud-core = { module = "org.incendo:cloud-core", version.ref = "cloud" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-paper" }
cloud-velocity = { module = "org.incendo:cloud-velocity", version.ref = "cloud-velocity" }
cloud-bungee = { module = "org.incendo:cloud-bungee", version.ref = "cloud-bungee" }
cloud-fabric = { module = "org.incendo:cloud-fabric", version.ref = "cloud-fabric" }
uuid-generator = { module = "com.fasterxml.uuid:java-uuid-generator", version.ref = "uuid-generator" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api" }
bungeecord-api = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord-api" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
jackson-toml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson" }
jackson-properties = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-properties", version.ref = "jackson" }